import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :delivest, DelivestWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :delivest, DelivestWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

config :delivest, :cookie_options,
  max_age: 30 * 24 * 60 * 60,
  http_only: false,
  secure: true,
  same_site: "Lax",
  path: "/"

config :ex_aws,
  access_key_id: System.get_env("S3_ACCESS_KEY") || raise("S3_ACCESS_KEY is missing"),
  secret_access_key: System.get_env("S3_SECRET_KEY") || raise("S3_SECRET_KEY is missing"),
  s3: [
    scheme: System.get_env("S3_SCHEME", "https://"),
    host: System.get_env("S3_HOST", "delivest-s3.shafranov.tech")
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
